package com.humana.humana_backend.modules.audit.model;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,

    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ORGANIZATION_SUSPENDED,
    ORGANIZATION_ACTIVATED,

    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    ROLE_ASSIGNED,
    ROLE_REMOVED,

    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_DEACTIVATED,

    LEAVE_REQUESTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED
}
